---
title: "Wei_Review"
author: "Jialu Wei"
date: "October 15, 2018"
output: html_document
---
1. All R codes run well
2. Data inspection well done
3. Data processing well done, even the sample_IDs are considered. Something can be improvement: loop can be used when generating files for each chromosome.
4. Visualiation part:
  i).Missing data and amount of heterozygosity : well done;
  ii). SNPs per Chromosome and which group contributes most: in the first plot (filteredSNPbyChr), all SNPs are counted but the defination of SNPs should be the ones have variation within group, so we can not see from the plot how many SNPs are in each chromosome; in the second plot (SNPbyGroup), this time the TRUE SNPs are shown. 
  I'm not sure if we should show the contribution of each group to each chromosome in one plot.
  
5. Check the files:
From the result of check1$Chromosome, there are NAs existing
From the result of check2$Positions, you may forget to invert position from chr to numeric.

```{r}
check1 <- read.csv("./maize_decreasing_1.csv",1)
check1$Chromosome
check1$Position

check2 <- read.csv("./teosinte_decreasing_10.csv",1)
check2$Chromosome
check2$Position
```